// ATLProject3.idl : IDL source for ATLProject3
//

// This file will be processed by the MIDL tool to
// produce the type library (ATLProject3.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(415ab462-5759-4d5c-bbd5-87b98f0eae98),
	version(1.0),
]
library ATLProject3Lib
{
	importlib("stdole2.tlb");
};

