// ATLProject1.idl : IDL source for ATLProject1
//

// This file will be processed by the MIDL tool to
// produce the type library (ATLProject1.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(511fd5ff-bdcf-4a8f-b140-10b0bd4872e8),
	version(1.0),
]
library ATLProject1Lib
{
	importlib("stdole2.tlb");
};

