// ATLProject3.idl : IDL source for ATLProject3
//

// This file will be processed by the MIDL tool to
// produce the type library (ATLProject3.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(61f516e7-a7bc-434d-a1fa-96963c3b0a87),
	version(1.0),
]
library ATLProject3Lib
{
	importlib("stdole2.tlb");
};

